name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the commit hash
        id: commit_hash
        run: |
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Build the Docker image
        run: |
          IMAGE_NAME="ghcr.io/${{ env.OWNER_LC }}/$(basename ${GITHUB_REPOSITORY}):${{ env.COMMIT_HASH }}"
          docker build --target production -t $IMAGE_NAME .
          
      - name: Push the Docker image
        run: |
          IMAGE_NAME="ghcr.io/${{ env.OWNER_LC }}/$(basename ${GITHUB_REPOSITORY}):${{ env.COMMIT_HASH }}"
          docker push $IMAGE_NAME

      - name: Tag the image with 'latest'
        run: |
          IMAGE_NAME="ghcr.io/${{ env.OWNER_LC }}/$(basename ${GITHUB_REPOSITORY}):latest"
          docker tag ghcr.io/${{ env.OWNER_LC }}/$(basename ${GITHUB_REPOSITORY}):${{ env.COMMIT_HASH }} $IMAGE_NAME
          docker push $IMAGE_NAME
